# Podcast Feed Settings
title:          Sermons by David Ollerton
email:          mail+podcast@rdsaunders.co.uk
description:    David Ollerton was born in Lancashire and always maintained his loyalty to The Red Rose of Lancashire, English rugby and Manchester United. He became a Christian in his teenage years and was always grateful for the firm biblical foundations laid in his life by Barrie Walton and the Free Methodist Church. David and Liz trained at Birmingham Bible Institute and then served with the London City Mission and churches in South Wales and Surrey for over forty years. They have two daughters and a son and six grandchildren. David was a keen mountaineer and enjoyed reading and woodwork, interests which his family shared with him. He learned Welsh, travelled widely and was involved with Welsh and English speaking churches. In recent years he founded [Waleswide/Cymrugyfan](http://www.waleswide.org/), a church planting, strengthening and training network.
subtitle:       "A collection of David's sermons from his ministry"
url:            https://www.davidollerton.wales
lang:           en-GB
author:         David Ollerton
copyright:      "&#x2117; &amp; &#xA9; 2017"
keywords:

# Pagination settings
paginate: 10

# SCSS Output
sass:
  style: :compressed

# Additional Jekyll Support
plugins:
  - jekyll-sitemap
